import { describe, expect, it } from "@jest/globals";

import { EngineKey } from "@/lib/types";

import {
  decodeSnapshot,
  type EmbedSnapshot,
  encodeSnapshot,
  estimateEmbedHeight,
} from "./embedState";

const snapshot: EmbedSnapshot = {
  code: "function add(a, b) { return a + b; }",
  engine: EngineKey.v8,
  flags: ["--print-bytecode"],
  output: "[generated bytecode for function: add]\n   17 S> Ldar a1\n   26 E> Add a0, [0]\n",
};

describe("encode/decode round trip", () => {
  it("restores every field", async () => {
    const decoded = await decodeSnapshot(await encodeSnapshot(snapshot));
    expect(decoded).toEqual(snapshot);
  });

  it("carries stderr and title when present", async () => {
    const full: EmbedSnapshot = {
      ...snapshot,
      stderr: "warning: something",
      title: "Adding two smis",
    };
    expect(await decodeSnapshot(await encodeSnapshot(full))).toEqual(full);
  });

  it("survives non-Latin1 source, which plain btoa cannot encode", async () => {
    const unicode: EmbedSnapshot = {
      ...snapshot,
      code: "const переменная = '🚀'",
      output: "λ → ∀",
    };
    const decoded = await decodeSnapshot(await encodeSnapshot(unicode));
    expect(decoded?.code).toBe(unicode.code);
    expect(decoded?.output).toBe(unicode.output);
  });

  it("produces a URL-safe payload with no characters needing escaping", async () => {
    const encoded = await encodeSnapshot(snapshot);
    expect(encoded).toMatch(/^[01][A-Za-z0-9_-]*$/);
    expect(encodeURIComponent(encoded)).toBe(encoded);
  });

  it("tags the payload with a version so the format can change later", async () => {
    expect(await encodeSnapshot(snapshot)).toMatch(/^[01]/);
  });

  it("handles a dump far larger than the chunk size of the base64 encoder", async () => {
    // The encoder batches at 0x8000 bytes; spreading the whole array instead
    // would overflow the argument limit and throw.
    const big: EmbedSnapshot = {
      ...snapshot,
      output: "Ldar a1\nAdd a0, [0]\nReturn\n".repeat(6000),
    };
    const decoded = await decodeSnapshot(await encodeSnapshot(big));
    expect(decoded?.output).toBe(big.output);
  });
});

describe("decode rejects unusable input", () => {
  it("returns null for an empty param", async () => {
    expect(await decodeSnapshot("")).toBeNull();
  });

  it("returns null for an unknown version marker", async () => {
    expect(await decodeSnapshot("9abc")).toBeNull();
  });

  it("returns null for a truncated payload rather than throwing", async () => {
    const encoded = await encodeSnapshot(snapshot);
    await expect(decodeSnapshot(encoded.slice(0, encoded.length - 12))).resolves.toBeNull();
  });

  it("returns null when the engine is not one we render", async () => {
    const forged =
      "0" + Buffer.from(JSON.stringify({ c: "x", n: "brainfuck", o: "y" })).toString("base64url");
    expect(await decodeSnapshot(forged)).toBeNull();
  });

  it("returns null when the output field is missing", async () => {
    const forged = "0" + Buffer.from(JSON.stringify({ c: "x", n: "v8" })).toString("base64url");
    expect(await decodeSnapshot(forged)).toBeNull();
  });
});

describe("estimateEmbedHeight", () => {
  it("grows with the dump but stays within the band", () => {
    const short = estimateEmbedHeight("one\ntwo");
    const long = estimateEmbedHeight("line\n".repeat(400));
    expect(short).toBeGreaterThanOrEqual(220);
    expect(long).toBeLessThanOrEqual(520);
    expect(long).toBeGreaterThan(short);
  });

  it("keeps a floor for an empty dump so the frame is not a sliver", () => {
    expect(estimateEmbedHeight("")).toBe(220);
  });
});
