apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: jslab

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: jslab-api
      context: apps/api
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*.ts"
          - "package.json"
          - "package-lock.json"
          - "tsconfig*.json"

    - image: jslab-frontend
      context: apps/frontend
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*"
          - "Dockerfile"

    - image: jslab-trace-service
      context: apps/trace-service
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*"
          - "config.ts"
          - "package.json"
          - "package-lock.json"
          - "tsconfig*.json"

    - image: jslab-engine-v8
      context: apps/engine-v8
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*.ts"
          - "package.json"
          - "package-lock.json"
          - "tsconfig*.json"

    - image: jslab-engine-hermes
      context: apps/engine-hermes
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*.ts"
          - "package.json"
          - "package-lock.json"
          - "tsconfig*.json"

    - image: jslab-engine-jsc
      context: apps/engine-jsc
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*.ts"
          - "package.json"
          - "package-lock.json"
          - "tsconfig*.json"

    - image: jslab-engine-spidermonkey
      context: apps/engine-spidermonkey
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
          - "src/**/*.ts"
          - "package.json"
          - "package-lock.json"
          - "tsconfig*.json"

manifests:
  kustomize:
    paths:
      - infra/k8s/dev
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone

deploy:
  kubectl:
    defaultNamespace: jslab

portForward:
  - resourceType: service
    resourceName: frontend
    namespace: jslab
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: trace-service
    namespace: jslab
    port: 8080
    localPort: 8085
  - resourceType: service
    resourceName: api
    namespace: jslab
    port: 8080
    localPort: 8080
