apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jslab
resources:
  - namespace.yaml
  - api-configmap.yaml
  - redis.yaml
  - api-deployment.yaml
  - trace-service.yaml
  - engine-v8.yaml
  - engine-hermes.yaml
  - engine-jsc.yaml
  - engine-spidermonkey.yaml
  - frontend.yaml
  - middleware.yaml
  - ingress.yaml
  - networkpolicy.yaml
