apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: engine-v8-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: engine-v8
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: engine-hermes-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: engine-hermes
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: engine-jsc-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: engine-jsc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: engine-spidermonkey-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: engine-spidermonkey
