apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jslab

resources:
  - ../base

images:
  # CI overrides these tags for each deploy (e.g. to the commit SHA).
  - name: pavlof01/jslab-api
    newTag: latest
  - name: pavlof01/jslab-engine-v8
    newTag: latest
  - name: pavlof01/jslab-engine-hermes
    newTag: latest
  - name: pavlof01/jslab-engine-jsc
    newTag: latest
  - name: pavlof01/jslab-engine-spidermonkey
    newTag: latest
  - name: pavlof01/jslab-frontend
    newTag: latest
