import { type V8SampleKey, v8Samples } from "@/lib/samples";
import { buildShareUrl } from "@/lib/shareState";
import { tools } from "@/lib/tools";
import { EngineKey } from "@/lib/types";
import { featuredIntrinsics } from "@/lib/v8Intrinsics";

export type Trace = {
  label: string;
  expr: string;
  result: string;
  steps: Array<[op: string, detail: string]>;
};

export const TRACES: Trace[] = [
  {
    label: "[] == ![]",
    expr: "[] == ![]",
    result: "true",
    steps: [
      ["ToBoolean", "[] → true, negated → false"],
      ["IsLooselyEqual", "[] == false"],
      ["ToNumber", "false → 0"],
      ["ToPrimitive", '[] → ""'],
      ["ToNumber", '"" → 0'],
    ],
  },
  {
    label: '"0" == false',
    expr: '"0" == false',
    result: "true",
    steps: [
      ["IsLooselyEqual", '"0" == false'],
      ["ToNumber", "false → 0"],
      ["IsLooselyEqual", '"0" == 0'],
      ["ToNumber", '"0" → 0'],
      ["IsStrictlyEqual", "0 === 0"],
    ],
  },
  {
    label: "[] + {}",
    expr: "[] + {}",
    result: '"[object Object]"',
    steps: [
      ["ApplyStringOrNumericBinaryOperator", "[] + {}"],
      ["ToPrimitive", '[] → ""'],
      ["ToPrimitive", '{} → "[object Object]"'],
      ["ToString", '"" → ""'],
      ["ToString", '"[object Object]" → "[object Object]"'],
    ],
  },
];

export type DumpLine = [pre: string, op?: string, post?: string];

export type Dump = {
  engine: EngineKey;
  name: string;
  short: string;
  flag: string;
  lines: DumpLine[];
  ops: Record<string, [signature: string, explanation: string]>;
  first: string;
};

export const DUMPS: Dump[] = [
  {
    engine: EngineKey.v8,
    name: "V8",
    short: "V8",
    flag: "--print-bytecode",
    lines: [
      ["[generated bytecode for function: add]"],
      ["Bytecode length: 12"],
      ["   17 S> [    0 : 0b 04    ", "Ldar", " a1]"],
      ["   26 E> [    2 : 3b 03 00 ", "Add", " a0, [0]]"],
      ["   31 S> [    5 : a9       ", "Return", "]"],
    ],
    ops: {
      Ldar: [
        "Ldar a1",
        "Load Accumulator from Register. Copies argument a1 into the accumulator — the implicit register every other Ignition bytecode reads from and writes to.",
      ],
      Add: [
        "Add a0, [0]",
        "Adds the accumulator to register a0 and records the operand types in feedback vector slot 0. Those recorded types are what Maglev and TurboFan later speculate on.",
      ],
      Return: [
        "Return",
        "Ends the function and hands whatever is in the accumulator back to the caller.",
      ],
    },
    first: "Add",
  },
  {
    engine: EngineKey.sm,
    name: "SpiderMonkey",
    short: "SpiderMonkey",
    flag: "dis()",
    lines: [
      ["loc     op"],
      ["-----   --"],
      ["00000:  ", "GetArg", " 0"],
      ["00003:  ", "GetArg", " 1"],
      ["00006:  ", "Add"],
      ["00007:  ", "Return"],
    ],
    ops: {
      GetArg: [
        "GetArg",
        "Pushes an argument onto the interpreter stack. SpiderMonkey is stack-based, so operands are pushed before the operation instead of naming registers.",
      ],
      Add: [
        "Add",
        "Pops the two top stack values, applies the addition operator to them and pushes the result. No register operands appear because there are none.",
      ],
      Return: ["Return", "Pops the top of the stack and returns it from the current script frame."],
    },
    first: "Add",
  },
  {
    engine: EngineKey.hermes,
    name: "Hermes",
    short: "Hermes",
    flag: "hbcdump",
    lines: [
      ["Function<add>(3 params, 2 registers):"],
      ["    ", "LoadParam", "        r1, 1"],
      ["    ", "LoadParam", "        r2, 2"],
      ["    ", "Add", "              r0, r1, r2"],
      ["    ", "Ret", "              r0"],
    ],
    ops: {
      LoadParam: [
        "LoadParam r1, 1",
        "Copies parameter 1 into register r1. Hermes numbers parameters from 1 because index 0 is this.",
      ],
      Add: [
        "Add r0, r1, r2",
        "Three-address form: adds r1 and r2 and writes the result into r0. Hermes bytecode is register-based and ahead-of-time compiled, so nothing here collects feedback.",
      ],
      Ret: ["Ret r0", "Returns the value held in r0."],
    },
    first: "Add",
  },
  {
    engine: EngineKey.jsc,
    name: "JavaScriptCore",
    short: "JSC",
    flag: "JSC_dumpBytecode=1",
    lines: [
      ["add#Ad3a4T: 5 instructions"],
      ["[   0] ", "enter"],
      ["[   1] ", "get_scope", "        loc4"],
      ["[   3] ", "add", "              loc5, arg1, arg2"],
      ["[   8] ", "ret", "              loc5"],
    ],
    ops: {
      enter: [
        "enter",
        "Prologue of a JavaScriptCore code block: initialises the frame and clears the locals it is responsible for.",
      ],
      get_scope: [
        "get_scope loc4",
        "Loads the scope of the executing function into a local, so later instructions can resolve variables through it.",
      ],
      add: [
        "add loc5, arg1, arg2",
        "Adds arg1 and arg2 into loc5. JSC also keeps profiling information per bytecode, which is what the DFG and FTL tiers compile against.",
      ],
      ret: ["ret loc5", "Returns the value in loc5 to the caller."],
    },
    first: "add",
  },
];

export const SNIPPET = `function add(a, b) {
  return a + b;
}`;

export const INTRINSICS: Array<[signature: string, explanation: string]> = featuredIntrinsics().map(
  (intrinsic) => [intrinsic.snippet.replace(/;$/, ""), intrinsic.description],
);

export type Study = { key: V8SampleKey; group: string; title: string; desc: string };

export const STUDIES: Study[] = [
  {
    key: "smiVsHeap",
    group: "numbers",
    title: "Smi vs HeapNumber",
    desc: "42 lives inside the pointer; 42.5 is a heap object. Print both and watch the move.",
  },
  {
    key: "arrayLengthHoley",
    group: "arrays",
    title: "length → HOLEY",
    desc: "Raising arr.length punches holes into the backing store, and HOLEY is permanent.",
  },
  {
    key: "arrayTypeTransitions",
    group: "arrays",
    title: "Element kind cascade",
    desc: "Smi → Double → Object, one way only. Push a float, then an object, and read the kind.",
  },
  {
    key: "arrayDeleteVsUndefined",
    group: "arrays",
    title: "delete vs undefined",
    desc: "delete a[1] leaves a hole, a[1] = undefined leaves a value. Only one keeps PACKED.",
  },
  {
    key: "arrayDictionaryMode",
    group: "arrays",
    title: "Sparse → dictionary",
    desc: "One assignment at index 100000 turns the flat store into a hash table.",
  },
  {
    key: "hiddenClassOrder",
    group: "objects",
    title: "Insertion order",
    desc: "Same properties, different order, different hidden class — %HaveSameMap answers false.",
  },
  {
    key: "hiddenClassDelete",
    group: "objects",
    title: "delete → slow properties",
    desc: "One delete drops the object into dictionary mode, and re-adding never brings it back.",
  },
  {
    key: "bytecodeDestructuring",
    group: "bytecode",
    title: "Destructuring",
    desc: "const [a, b] = arr is the iterator protocol, not sugar. The bytecode shows the cost.",
  },
  {
    key: "argumentsVsRest",
    group: "bytecode",
    title: "arguments vs rest",
    desc: "CreateMappedArguments and its parameter aliasing, next to a plain array from ...args.",
  },
  {
    key: "consString",
    group: "strings",
    title: "ConsString",
    desc: "s1 + s2 copies nothing: two pointers, flattened later only if an operation demands it.",
  },
  {
    key: "deoptTypeChange",
    group: "jit",
    title: "Deopt on type change",
    desc: "Ten thousand integer calls, then one string — --trace-deopt prints the bail-out.",
  },
  {
    key: "icMonomorphic",
    group: "jit",
    title: "Monomorphic → megamorphic",
    desc: "One shape, then two, then five: the same call site degrading through every IC state.",
  },
];

export function studyHref(key: V8SampleKey): string {
  return buildShareUrl("", "/playground", {
    code: v8Samples[key],
    engines: [EngineKey.v8],
    flags: { [EngineKey.v8]: ["--print-bytecode", "--allow-natives-syntax"] },
  });
}

export type ToolRow = { n: string; href: string; name: string; kind: string; desc: string };

export const TOOL_ROWS: ToolRow[] = tools.map((tool, i) => ({
  n: String(i + 1).padStart(2, "0"),
  href: tool.href,
  name: tool.label,
  kind: tool.kind,
  desc: tool.detail ?? tool.description,
}));

export const ALSO: Array<[label: string, text: string]> = [
  [
    "opcode reference",
    "Every opcode of all four engines, documented. Click one anywhere and the explanation opens.",
  ],
  ["shareable", "Any state — snippet, engine, trace step — is a URL. Send it; they see your view."],
  ["embeddable", "It also embeds, so a trace can be the figure instead of a screenshot of one."],
  ["deopt traces", "Drop in a --prof log: hottest functions, and why each one deoptimised."],
  ["open source", "MIT. Read it, fork it, file the bug you just found."],
  ["nothing in the way", "Browser only. No install, no account, no payment, no plans."],
];
