import { Box, Container, Flex, Heading, HStack, SimpleGrid, Text, VStack } from "@chakra-ui/react";
import { HighlightedCode } from "@/components/OutputsPanel/CodeBlock";
import { EngineKey } from "@/lib/types";

const displayFont = "'Plus Jakarta Sans', Inter, var(--font-sans), sans-serif";
const subtleBorder = "rgba(255,255,255,0.08)";
const cardBorder = "rgba(255,255,255,0.1)";
const mutedText = "rgba(255,255,255,0.62)";

const mockBytecodeResponseV8 = `
[generated bytecode for function:  (0xfebe0101c061 <SharedFunctionInfo>)]
Bytecode length: 24
Parameter count 1
Register count 3
Frame size 24
         0x4010000a0 @    0 : 13 00             LdaConstant [0:0xfebe0101c0b1 <FixedArray[2]>]
         0x4010000a2 @    2 : d1                Star1
         0x4010000a3 @    3 : 1b fe f7          Mov <closure>, r2
         0x4010000a6 @    6 : 6e 6e 01 f8 02    CallRuntime [DeclareGlobals], r1-r2
         0x4010000ab @   11 : 23 01 00          LdaGlobal [1:"f"], FBV[0]
         0x4010000ae @   14 : d1                Star1
         0x4010000af @   15 : 0d 29             LdaSmi [41]
         0x4010000b1 @   17 : d0                Star2
         0x4010000b2 @   18 : 6b f8 f7 02       CallUndefinedReceiver1 r1, r2, FBV[2]
         0x4010000b6 @   22 : d2                Star0
         0x4010000b7 @   23 : b7                Return
Constant pool (size = 2)
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function: f (0xfebe0101c0c1 <SharedFunctionInfo f>)]
Bytecode length: 6
Parameter count 2
Register count 0
Frame size 0
         0x4010000e0 @    0 : 0b 03             Ldar a0
         0x4010000e2 @    2 : 4d 01 00          AddSmi [1], FBV[0]
         0x4010000e5 @    5 : b7                Return
Constant pool (size = 0)
Handler Table (size = 0)
Source Position Table (size = 0)
`;

const mockBytecodeResponseSm = `
{
  "file": "-e line 24 > Function",
  "lineno": 1,
  "column": 1,
  "immutableFlags": [
    "IsFunction",
    "HasInnerFunctions",
    "HasMappedArgsObj"
  ],
  "functionName": "anonymous",
  "functionFlags": [
    "NORMAL_KIND",
    "BASESCRIPT",
    "CONSTRUCTOR",
    "LAMBDA"
  ]
}
loc   line  op
----- ----  --
main:
00000:   2  Lambda function f(x){ return x + 1 } # FUN
00005:   2  SetLocal 0                  # FUN
00009:   2  Pop                         #
00010:   4  GetLocal 0                  # f
00014:   4  Undefined                   # f undefined
00015:   4  Int8 41                     # f undefined 41
00017:   4  CallIgnoresRv 1             # f(...)
00020:   4  Pop                         #
00021:   5  RetRval                     #

Source notes:
 ofs line column    pc  delta desc             args
---- ---- ------ ----- ------ ---------------- ------
  0:    1      1     0 [   0] newline
  1:    2      1    10 [  10] setline          lineno 4
  3:    4      1    10 [   0] breakpoint-step-sep
  4:    4      1    17 [   7] colspan          colspan 1
  6:    4      2    17 [   0] breakpoint
  7:    4      2    21 [   4] newline
  8:    5      1    21 [   0] breakpoint

Exception table:
kind               stack    start      end

Scope notes:
   index   parent    start      end

GC things:
   index   type       value
       0   Scope      function {
                         0: var f (frame slot 0)
                      } -> global
       1   Function   f @ 3:11
`;

const mockBytecodeResponseJsc = `
<global>#BsVRHf:[0xffffa34a0150->0xffffa507ca88, NoneGlobal, 54]: 11 instructions (0 16-bit instructions, 0 32-bit instructions, 5 instructions with metadata); 158 bytes (104 metadata bytes); 1 parameter(s); 14 callee register(s); 5 variable(s); scope at loc4

bb#1
Predecessors: [ ]
[   0] enter
[   1] new_func           dst:loc5, scope:loc4, functionDecl:0
[   5] resolve_scope      dst:loc6, scope:loc4, var:0, resolveType:GlobalProperty, localScopeDepth:0
[  12] mov                dst:loc7, src:loc6
[  15] put_to_scope       scope:loc7, var:0, value:loc5, getPutInfo:2048<ThrowIfNotFound|GlobalProperty|NotInitialization|NotStrictMode>, symbolTableOrScopeDepth:0, offset:0
[  23] mov                dst:loc5, src:Undefined(const0)
[  26] resolve_scope      dst:loc8, scope:loc4, var:0, resolveType:GlobalProperty, localScopeDepth:0
[  33] get_from_scope     dst:loc5, scope:loc8, var:0, getPutInfo:2048<ThrowIfNotFound|GlobalProperty|NotInitialization|NotStrictMode>, localScopeDepth:0, offset:0, valueProfile:1
[  42] mov                dst:loc7, src:Int32: 41(const1)
[  45] call               dst:loc5, callee:loc5, argc:2, argv:14, valueProfile:2
[  52] end                value:loc5
Successors: [ ]


Identifiers:
  id0 = f

Constants:
   k0 = Undefined
   k1 = Int32: 41: in source as integer

f#AtJJJ0:[0xffffa34a0260->0xffffa3475900, NoneFunctionCall, 9]: 3 instructions (0 16-bit instructions, 0 32-bit instructions, 0 instructions with metadata); 9 bytes (0 metadata bytes); 2 parameter(s); 6 callee register(s); 5 variable(s); scope at loc4

bb#1
Predecessors: [ ]
[   0] enter
[   1] add                dst:loc5, lhs:arg1, rhs:Int32: 1(const0), profileIndex:0, operandTypes:OperandTypes(126, 3)
[   7] ret                value:loc5
Successors: [ ]


Constants:
   k0 = Int32: 1: in source as integer
`;

const mockBytecodeResponseHermes = `
<global>#BsVRHf:[0xffffa34a0150->0xffffa507ca88, NoneGlobal, 54]: 11 instructions (0 16-bit instructions, 0 32-bit instructions, 5 instructions with metadata); 158 bytes (104 metadata bytes); 1 parameter(s); 14 callee register(s); 5 variable(s); scope at loc4

bb#1
Predecessors: [ ]
[   0] enter
[   1] new_func           dst:loc5, scope:loc4, functionDecl:0
[   5] resolve_scope      dst:loc6, scope:loc4, var:0, resolveType:GlobalProperty, localScopeDepth:0
[  12] mov                dst:loc7, src:loc6
[  15] put_to_scope       scope:loc7, var:0, value:loc5, getPutInfo:2048<ThrowIfNotFound|GlobalProperty|NotInitialization|NotStrictMode>, symbolTableOrScopeDepth:0, offset:0
[  23] mov                dst:loc5, src:Undefined(const0)
[  26] resolve_scope      dst:loc8, scope:loc4, var:0, resolveType:GlobalProperty, localScopeDepth:0
[  33] get_from_scope     dst:loc5, scope:loc8, var:0, getPutInfo:2048<ThrowIfNotFound|GlobalProperty|NotInitialization|NotStrictMode>, localScopeDepth:0, offset:0, valueProfile:1
[  42] mov                dst:loc7, src:Int32: 41(const1)
[  45] call               dst:loc5, callee:loc5, argc:2, argv:14, valueProfile:2
[  52] end                value:loc5
Successors: [ ]


Identifiers:
  id0 = f

Constants:
   k0 = Undefined
   k1 = Int32: 41: in source as integer

f#AtJJJ0:[0xffffa34a0260->0xffffa3475900, NoneFunctionCall, 9]: 3 instructions (0 16-bit instructions, 0 32-bit instructions, 0 instructions with metadata); 9 bytes (0 metadata bytes); 2 parameter(s); 6 callee register(s); 5 variable(s); scope at loc4

bb#1
Predecessors: [ ]
[   0] enter
[   1] add                dst:loc5, lhs:arg1, rhs:Int32: 1(const0), profileIndex:0, operandTypes:OperandTypes(126, 3)
[   7] ret                value:loc5
Successors: [ ]


Constants:
   k0 = Int32: 1: in source as integer
`;

const engines = [
  { key: EngineKey.v8, label: "V8", tagline: "Google Chrome · Node.js", out: mockBytecodeResponseV8 },
  { key: EngineKey.sm, label: "SpiderMonkey", tagline: "Firefox · SpiderNode", out: mockBytecodeResponseSm },
  { key: EngineKey.jsc, label: "JavaScriptCore", tagline: "Safari · Bun", out: mockBytecodeResponseJsc },
  { key: EngineKey.hermes, label: "Hermes", tagline: "React Native", out: mockBytecodeResponseHermes },
] as const;

export function BytecodeSection() {
  return (
    <Box
      as="section"
      position="relative"
      borderTopWidth="1px"
      borderColor={subtleBorder}
      bg="brandAlpha.50"
      px={{ base: 4, sm: 6, md: 20 }}
      py={{ base: 12, sm: 16, md: 20 }}
    >
      <Box aria-hidden="true" position="absolute" inset={0} pointerEvents="none" overflow="hidden">
        <Box
          position="absolute"
          bottom="-6rem"
          left="30%"
          h="20rem"
          w="20rem"
          borderRadius="full"
          bg="brandAlpha.50"
          filter="blur(100px)"
        />
      </Box>

      <Container maxW="7xl" px={0} position="relative">
        <VStack gap={{ base: 10, md: 14 }} align="stretch">
          <VStack gap={4} textAlign="center">
            <Text color="brand.300" fontSize="xs" fontWeight="700" letterSpacing="0.3em" textTransform="uppercase">
              Under the Hood
            </Text>
            <Heading
              as="h2"
              fontFamily={displayFont}
              fontSize={{ base: "2xl", md: "4xl" }}
              fontWeight="900"
              letterSpacing="-0.04em"
            >
              Same Code. Different Bytecode.
            </Heading>
            <Text color={mutedText} fontSize="base" lineHeight="1.8" maxW="2xl">
              Every JavaScript engine compiles your code differently. Here&apos;s how{" "}
              <Text as="span" color="white" fontWeight="600">
                function f(x){" {"} return x + 1 {"}"}
              </Text>{" "}
              looks after compilation — each engine produces its own bytecode format, register allocation strategy, and
              instruction set.
            </Text>
          </VStack>

          <SimpleGrid columns={{ base: 1, md: 2 }} gap={5}>
            {engines.map((engine) => (
              <Box
                key={engine.key}
                borderWidth="1px"
                borderColor={cardBorder}
                borderRadius="2xl"
                overflow="hidden"
                display="flex"
                flexDirection="column"
                transition="border-color 0.2s ease"
                _hover={{ borderColor: "rgba(249,227,26,0.25)" }}
              >
                <Flex
                  px={4}
                  py={3}
                  align="center"
                  justify="space-between"
                  bg="surface.200"
                  borderBottomWidth="1px"
                  borderColor={cardBorder}
                  flexShrink={0}
                >
                  <HStack gap={3}>
                    <Text fontSize="sm" fontWeight="700" fontFamily={displayFont}>
                      {engine.label}
                    </Text>
                  </HStack>
                  <Text fontSize="xs" color={mutedText} fontWeight="500">
                    {engine.tagline}
                  </Text>
                </Flex>
                <HighlightedCode
                  engineKey={engine.key}
                  out={engine.out}
                  showDiff={false}
                  boxProps={{ maxH: "320px", overflow: "auto" }}
                />
              </Box>
            ))}
          </SimpleGrid>
        </VStack>
      </Container>
    </Box>
  );
}
