"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { KeyboardEvent as ReactKeyboardEvent, PointerEvent as ReactPointerEvent } from "react";
import { Box, Button, Flex, For, HStack, Menu, Portal, Text } from "@chakra-ui/react";
import { Global } from "@emotion/react";
import { HeaderBar } from "../components/HeaderBar";
import { EditorPanel } from "../components/EditorPanel";
import { OutputsPanel } from "../components/OutputsPanel";
import type {
  ApiResponse,
  EngineKey,
  EngineResult,
  RunStatus,
  SampleDescriptor,
  V8FlagOption,
  VersionsResp,
} from "../lib/types";
import { useColorModeValue } from "@/components/ui/color-mode";
import EngineCheckboxSelector from "@/components/EngineCheckboxSelector";
import { RadioCardItem, RadioCardLabel, RadioCardRoot } from "@/components/ui/radio-card";

const MIN_SPLIT = 0.25;
const MAX_SPLIT = 0.75;

const samples: Record<string, string> = {
  add: `function f(x){ return x + 1 }\nf(41);`,
  closure: `function f(a){ function g(b){ return a + b } return g(1) }\nf(41);`,
  loop: `function f(n){ let s=0; for(let i=0;i<n;i++) s+=i; return s }\nf(10);`,
  try: `function f(){ try { throw 1 } catch(e){ return e + 1 } }\nf();`,
  d8Native: `function hot(x){ return x + 1; }\nfor (let i = 0; i < 5000; i++) hot(i);\nif (typeof globalThis.d8 !== "undefined") {\n  eval('%OptimizeFunctionOnNextCall(hot);');\n}\nprint('hot(41)=', hot(41));`,
  typedarray: `const buffer = new ArrayBuffer(16);\nconst view = new DataView(buffer);\nview.setUint32(0, 0xdeadbeef, true);\nview.setFloat64(8, Math.PI, true);\nconst bytes = Array.from(new Uint8Array(buffer)).map((b) => b.toString(16).padStart(2, '0'));\nprint('buffer bytes:', bytes.join(' '));\nprint('float64:', view.getFloat64(8, true).toFixed(6));`,
  asyncFlow: `async function loadUser(id){\n  return { id, name: 'user-' + id };\n}\nasync function main(){\n  const users = await Promise.all([1, 2, 3].map((id) => loadUser(id)));\n  const names = users.map((u) => u.name).join(', ');\n  print('async users:', names);\n}\nmain();`,
  generator: `function* fibonacci(limit){\n  let a = 0, b = 1;\n  while (limit-- > 0) {\n    yield a;\n    [a, b] = [b, a + b];\n  }\n}\nprint('fib:', [...fibonacci(8)].join(', '));`,
};

type SampleKey = keyof typeof samples;

const sampleCatalog: SampleDescriptor[] = [
  { key: "add", label: "Add", description: "Minimal function call returning 42." },
  { key: "closure", label: "Closure", description: "Capturing outer scope and invoking inner function." },
  { key: "loop", label: "Loop", description: "Simple for-loop summing integer range." },
  { key: "try", label: "Try/catch", description: "Exception handling flow returning a computed value." },
  { key: "d8Native", label: "d8 native", description: "Uses V8 % intrinsics to optimise a hot function." },
  { key: "typedarray", label: "Typed arrays", description: "Manipulates ArrayBuffer via DataView, prints bytes." },
  { key: "asyncFlow", label: "Async flow", description: "Async/await fetching mock users in parallel." },
  { key: "generator", label: "Generator", description: "Generates Fibonacci numbers via iterator." },
];

const tabs: { key: EngineKey; label: string }[] = [
  { key: "v8", label: "V8" },
  { key: "sm", label: "SpiderMonkey" },
  { key: "hermes", label: "Hermes" },
  { key: "jsc", label: "JSC" },
];

const v8NativeIntrinsics = [
  {
    name: "%OptimizeFunctionOnNextCall",
    insertText: "%OptimizeFunctionOnNextCall(${1:function});",
    detail: "V8 native · Optimise function on its next invocation",
  },
  {
    name: "%PrepareFunctionForOptimization",
    insertText: "%PrepareFunctionForOptimization(${1:function});",
    detail: "V8 native · Marks function so optimisation can be triggered",
  },
  {
    name: "%GetOptimizationStatus",
    insertText: "%GetOptimizationStatus(${1:function});",
    detail: "V8 native · Returns optimisation state bits",
  },
  {
    name: "%DebugPrint",
    insertText: "%DebugPrint(${1:value});",
    detail: "V8 native · Prints internal representation of value",
  },
  {
    name: "%DebugTrace",
    insertText: "%DebugTrace();",
    detail: "V8 native · Enables tracing for following execution",
  },
  {
    name: "%DisassembleFunction",
    insertText: "%DisassembleFunction(${1:function});",
    detail: "V8 native · Dumps generated code for the function",
  },
  {
    name: "%CollectGarbage",
    insertText: "%CollectGarbage(${1:space});",
    detail: "V8 native · Runs garbage collector for provided space",
  },
];

const v8FlagOptions: V8FlagOption[] = [
  {
    flag: "--allow-natives-syntax",
    label: "allow-natives-syntax",
    description: "Enable %intrinsics like %OptimizeFunctionOnNextCall",
  },
  {
    flag: "--print-bytecode",
    label: "print-bytecode",
    description: "Dump generated bytecode for executed functions",
  },
  {
    flag: "--print-ast",
    label: "print-ast",
    description: "Print parsed AST to stderr before execution",
  },
  {
    flag: "--print-code",
    label: "print-code",
    description: "Disassemble generated machine code for all compiled functions",
  },
  {
    flag: "--print-opt-code",
    label: "print-opt-code",
    description: "Emit optimised machine code for hot functions",
  },
  {
    flag: "--print-regexp-bytecode",
    label: "print-regexp-bytecode",
    description: "Dump regexp interpreter bytecode for compiled patterns",
  },
  {
    flag: "--print-regexp-code",
    label: "print-regexp-code",
    description: "Show generated native code for regexp execution",
  },
  {
    flag: "--trace-opt",
    label: "trace-opt",
    description: "Trace optimisation decisions made by the compiler",
  },
  {
    flag: "--trace-opt-verbose",
    label: "trace-opt-verbose",
    description: "Verbose optimiser trace including detailed pipeline stages",
  },
  {
    flag: "--trace-deopt",
    label: "trace-deopt",
    description: "Log deoptimisation events with reasons and bailout locations",
  },
  {
    flag: "--trace-ic",
    label: "trace-ic",
    description: "Log inline cache state transitions during execution",
  },
];

export default function Page() {
  const [code, setCode] = useState(samples.add);
  const [engines, setEngines] = useState<Record<EngineKey, boolean>>({
    v8: true,
    sm: false,
    hermes: false,
    jsc: false,
  });
  const [status, setStatus] = useState<RunStatus>("idle");
  const [out, setOut] = useState<Record<EngineKey, EngineResult>>({
    v8: { exitCode: null, stdout: "", stderr: "" },
    sm: { exitCode: null, stdout: "", stderr: "" },
    hermes: { exitCode: null, stdout: "", stderr: "" },
    jsc: { exitCode: null, stdout: "", stderr: "" },
  });
  const [meta, setMeta] = useState<string>("");
  const [activeTab, setActiveTab] = useState<EngineKey>("v8");
  const [versions, setVersions] = useState<Record<EngineKey, string>>({ v8: "", sm: "", hermes: "", jsc: "" });
  const [activeSample, setActiveSample] = useState<SampleKey | null>("add");
  const [panelSplit, setPanelSplit] = useState(0.55);
  const [selectedV8Flag, setSelectedV8Flag] = useState<string | null>("--print-bytecode");
  const [samplesOpen, setSamplesOpen] = useState(true);

  const editorRef = useRef<any>(null);
  const monacoRef = useRef<any>(null);
  const decorationsRef = useRef<string[]>([]);
  const completionRef = useRef<any>(null);
  const gridRef = useRef<HTMLDivElement | null>(null);
  const sampleApplyRef = useRef<SampleKey | null>("add");
  const resizeCleanupRef = useRef<(() => void) | null>(null);

  const pageBg = useColorModeValue("#f8fafc", "#0f172a");
  const panelBg = useColorModeValue("#ffffff", "#1e293b");
  const borderColor = useColorModeValue("#e2e8f0", "#334155");
  const splitterBg = useColorModeValue("#e2e8f0", "#475569");
  const splitterGripBg = useColorModeValue("#94a3b8", "#94a3b8");
  const textPrimary = useColorModeValue("#0f172a", "#e2e8f0");

  const activeSampleMeta = useMemo(
    () => sampleCatalog.find((item) => item.key === activeSample) || null,
    [activeSample]
  );
  const selectedV8Flags = useMemo(() => (selectedV8Flag ? [selectedV8Flag] : []), [selectedV8Flag]);

  const selectedEngines = useMemo(() => (Object.keys(engines) as EngineKey[]).filter((key) => engines[key]), [engines]);

  const handleEnginesChange = useCallback((values: string[]) => {
    setEngines((prev) => {
      const base: Record<EngineKey, boolean> = { v8: false, sm: false, hermes: false, jsc: false };
      if (values.length === 0) {
        const fallback = (Object.keys(prev) as EngineKey[]).find((key) => prev[key]) ?? "v8";
        base[fallback] = true;
        return base;
      }
      values.forEach((value) => {
        if ((["v8", "sm", "hermes", "jsc"] as EngineKey[]).includes(value as EngineKey)) {
          base[value as EngineKey] = true;
        }
      });
      return base;
    });
  }, []);

  const enabledTabs = useMemo(() => tabs.filter((tab) => engines[tab.key]), [engines]);
  const activeTabIndex = useMemo(() => {
    const idx = enabledTabs.findIndex((tab) => tab.key === activeTab);
    return idx >= 0 ? idx : 0;
  }, [enabledTabs, activeTab]);

  useEffect(() => {
    if (enabledTabs.length === 0) return;
    if (!enabledTabs.some((tab) => tab.key === activeTab)) {
      setActiveTab(enabledTabs[0].key);
    }
  }, [enabledTabs, activeTab]);

  const onMount = useCallback((editor: any, monaco: any) => {
    editorRef.current = editor;
    monacoRef.current = monaco;
    monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
      noSemanticValidation: false,
      noSyntaxValidation: false,
      diagnosticCodesToIgnore: [1109],
    });
    completionRef.current?.dispose?.();
    completionRef.current = monaco.languages.registerCompletionItemProvider("javascript", {
      triggerCharacters: ["%"],
      provideCompletionItems(model: any, position: any) {
        const word = model.getWordUntilPosition(position);
        const beforeWordRange = new monaco.Range(
          position.lineNumber,
          Math.max(1, word.startColumn - 1),
          position.lineNumber,
          word.startColumn
        );
        const beforeWord = model.getValueInRange(beforeWordRange);
        const startColumn = beforeWord === "%" ? Math.max(1, word.startColumn - 1) : word.startColumn;
        const range = new monaco.Range(position.lineNumber, startColumn, position.lineNumber, word.endColumn);

        const suggestions = v8NativeIntrinsics.map((intrinsic) => ({
          label: intrinsic.name,
          kind: monaco.languages.CompletionItemKind.Function,
          detail: intrinsic.detail,
          documentation: "Requires --allow-natives-syntax when running d8.",
          insertText: intrinsic.insertText,
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
        }));

        return { suggestions };
      },
    });
  }, []);

  useEffect(() => () => completionRef.current?.dispose?.(), []);

  useEffect(() => {
    const editor = editorRef.current;
    const monaco = monacoRef.current;
    if (!editor || !monaco) return;
    const model = editor.getModel();
    if (!model) return;

    const matches = model.findMatches("%[A-Za-z_][A-Za-z0-9_]*", false, true, false, null, true);
    const decorations = matches.map((match: { range: any }) => ({
      range: match.range,
      options: { inlineClassName: "token-native-intrinsic" },
    }));
    decorationsRef.current = editor.deltaDecorations(decorationsRef.current, decorations);
  }, [code]);

  useEffect(() => {
    return () => {
      const editor = editorRef.current;
      if (editor && decorationsRef.current.length > 0) {
        editor.deltaDecorations(decorationsRef.current, []);
      }
    };
  }, []);

  const handleEditorChange = useCallback(
    (value?: string) => {
      const next = value ?? "";
      setCode(next);
      if (sampleApplyRef.current) {
        sampleApplyRef.current = null;
      } else if (activeSample !== null) {
        setActiveSample(null);
      }
    },
    [activeSample]
  );

  const clampSplit = useCallback((value: number) => Math.min(MAX_SPLIT, Math.max(MIN_SPLIT, value)), []);

  const adjustSplit = useCallback(
    (delta: number) => {
      setPanelSplit((prev) => clampSplit(prev + delta));
    },
    [clampSplit]
  );

  const handleSplitterPointerDown = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      event.preventDefault();
      const grid = gridRef.current;
      if (!grid) return;

      resizeCleanupRef.current?.();

      const handleMove = (pointerEvent: PointerEvent) => {
        const rect = grid.getBoundingClientRect();
        if (rect.width <= 0) return;
        const ratio = (pointerEvent.clientX - rect.left) / rect.width;
        if (!Number.isFinite(ratio)) return;
        setPanelSplit(clampSplit(ratio));
      };

      const handleUp = () => {
        resizeCleanupRef.current?.();
      };

      const cleanup = () => {
        window.removeEventListener("pointermove", handleMove);
        window.removeEventListener("pointerup", handleUp);
        window.removeEventListener("pointercancel", handleUp);
        document.body.classList.remove("resizing-cursor");
        resizeCleanupRef.current = null;
      };

      resizeCleanupRef.current = cleanup;

      window.addEventListener("pointermove", handleMove);
      window.addEventListener("pointerup", handleUp, { once: true });
      window.addEventListener("pointercancel", handleUp, { once: true });
      document.body.classList.add("resizing-cursor");
    },
    [clampSplit]
  );

  const handleSplitterKey = useCallback(
    (event: ReactKeyboardEvent<HTMLDivElement>) => {
      if (event.key === "ArrowLeft") {
        event.preventDefault();
        adjustSplit(-0.03);
      } else if (event.key === "ArrowRight") {
        event.preventDefault();
        adjustSplit(0.03);
      } else if (event.key === "Home") {
        event.preventDefault();
        setPanelSplit(MIN_SPLIT);
      } else if (event.key === "End") {
        event.preventDefault();
        setPanelSplit(MAX_SPLIT);
      }
    },
    [adjustSplit]
  );

  const handleSplitterDoubleClick = useCallback(() => {
    setPanelSplit(0.5);
  }, []);

  useEffect(() => () => resizeCleanupRef.current?.(), []);

  useEffect(() => {
    (async () => {
      try {
        const response = await fetch("/api/versions", { cache: "no-store" });
        const data: VersionsResp = await response.json();
        const collected: Record<EngineKey, string> = { v8: "", sm: "", hermes: "", jsc: "" };
        (Object.keys(collected) as EngineKey[]).forEach((key) => {
          const info = data?.engines?.[key];
          collected[key] = info?.ok ? info.short || "ok" : "unavailable";
        });
        setVersions(collected);
      } catch {
        setVersions({ v8: "n/a", sm: "n/a", hermes: "n/a", jsc: "n/a" });
      }
    })();
  }, []);

  const run = useCallback(async () => {
    setStatus("running");
    setOut({
      v8: { exitCode: null, stdout: "", stderr: "" },
      sm: { exitCode: null, stdout: "", stderr: "" },
      hermes: { exitCode: null, stdout: "", stderr: "" },
      jsc: { exitCode: null, stdout: "", stderr: "" },
    });
    setMeta("");

    try {
      const response = await fetch("/api/bytecode", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ code, engines: selectedEngines, v8Flags: selectedV8Flags }),
      });
      const data: ApiResponse = await response.json();
      if (!data.ok) throw new Error(data.error || "Request failed");

      const results = data.results || {};
      setOut({
        v8: {
          exitCode: results.v8?.exitCode ?? null,
          stdout: (results.v8?.stdout ?? "").trim(),
          stderr: (results.v8?.stderr ?? "").trim(),
          ms: results.v8?.ms,
        },
        sm: {
          exitCode: results.sm?.exitCode ?? null,
          stdout: (results.sm?.stdout ?? "").trim(),
          stderr: (results.sm?.stderr ?? "").trim(),
          ms: results.sm?.ms,
        },
        hermes: {
          exitCode: results.hermes?.exitCode ?? null,
          stdout: (results.hermes?.stdout ?? "").trim(),
          stderr: (results.hermes?.stderr ?? "").trim(),
          ms: results.hermes?.ms,
        },
        jsc: {
          exitCode: results.jsc?.exitCode ?? null,
          stdout: (results.jsc?.stdout ?? "").trim(),
          stderr: (results.jsc?.stderr ?? "").trim(),
          ms: results.jsc?.ms,
        },
      });
      if (data.meta) setMeta(`Duration: ${data.meta.ms} ms`);
      setStatus("done");
    } catch (error: any) {
      setStatus("error");
      setMeta(error?.message || "Error");
    }
  }, [code, selectedEngines, selectedV8Flags]);

  const setSample = (key: SampleKey) => {
    sampleApplyRef.current = key;
    setActiveSample(key);
    setCode(samples[key]);
    setMeta(`Loaded sample: ${sampleCatalog.find((item) => item.key === key)?.label ?? key}`);
    requestAnimationFrame(() => {
      editorRef.current?.focus?.();
    });
  };

  return (
    <>
      <Global
        styles={`
          .token-native-intrinsic { color: #f59e0b; font-weight: 600; }
          body.resizing-cursor, body.resizing-cursor * { cursor: col-resize !important; }
        `}
      />
      <Flex direction="column" minH="100vh" bg={pageBg} color={textPrimary}>
        <Box as="header" px={6} py={4} borderBottom="1px solid" borderColor={borderColor} bg={panelBg}>
          <HeaderBar onRun={run} status={status} meta={meta} versions={versions} />
        </Box>

        <Flex ref={gridRef} gap={4} flex="1" px={6} py={4} align="stretch">
          <Box
            bg={panelBg}
            border="1px solid"
            borderColor={borderColor}
            borderRadius="lg"
            display="flex"
            flexDirection="column"
            overflow="hidden"
            minH={0}
            flexGrow={panelSplit}
            flexShrink={1}
            flexBasis="0%"
          >
            <HStack borderBottom="1px solid" borderColor={borderColor}>
              <Box px={5} py={4}>
                <Text fontWeight="semibold">Editor</Text>
              </Box>
              <Menu.Root>
                <Menu.Trigger asChild>
                  <Button variant="solid" size="sm">
                    V8 Flag: {selectedV8Flag}
                  </Button>
                </Menu.Trigger>
                <Portal>
                  <Menu.Positioner>
                    <Menu.Content>
                      <For each={v8FlagOptions}>
                        {(option) => (
                          <Menu.Item value={option.flag}>
                            <RadioCardRoot
                              defaultValue={"--print-bytecode"}
                              value={selectedV8Flag}
                              onValueChange={(e) => setSelectedV8Flag(e.value)}
                              w="100%"
                            >
                              <RadioCardLabel />
                              <RadioCardItem label={option.flag} value={option.flag} addon={option.description} />
                            </RadioCardRoot>
                          </Menu.Item>
                        )}
                      </For>
                    </Menu.Content>
                  </Menu.Positioner>
                </Portal>
              </Menu.Root>
            </HStack>
            <EditorPanel
              code={code}
              onCodeChange={handleEditorChange}
              onEditorMount={onMount}
              samples={sampleCatalog}
              activeSampleKey={activeSample}
              activeSampleDescription={activeSampleMeta?.description ?? null}
              onSelectSample={(key) => setSample(key as SampleKey)}
              samplesOpen={samplesOpen}
              onToggleSamples={() => setSamplesOpen((open) => !open)}
            />
          </Box>

          <Box
            role="separator"
            aria-orientation="vertical"
            aria-valuenow={Math.round(panelSplit * 100)}
            aria-valuemin={MIN_SPLIT * 100}
            aria-valuemax={MAX_SPLIT * 100}
            tabIndex={0}
            onPointerDown={handleSplitterPointerDown}
            onDoubleClick={handleSplitterDoubleClick}
            onKeyDown={handleSplitterKey}
            display="flex"
            alignItems="center"
            justifyContent="center"
            bg={splitterBg}
            borderRadius="full"
            cursor="col-resize"
            minH="160px"
            flex="0 0 12px"
            w="12px"
          >
            <Box w="4px" h="32px" borderRadius="full" bg={splitterGripBg} />
          </Box>

          <Box
            bg={panelBg}
            border="1px solid"
            borderColor={borderColor}
            borderRadius="lg"
            display="flex"
            flexDirection="column"
            overflow="hidden"
            minH={0}
            flexGrow={Math.max(0.1, 1 - panelSplit)}
            flexShrink={1}
            flexBasis="0%"
          >
            <HStack px={4} py={4} borderBottom="1px solid" borderColor={borderColor}>
              <Text fontWeight="semibold">Outputs</Text>
              <EngineCheckboxSelector
                selectedEngines={selectedEngines}
                onEnginesChange={handleEnginesChange}
                tabs={tabs}
              />
            </HStack>
            <OutputsPanel enabledTabs={enabledTabs} activeTabIndex={activeTabIndex} out={out} versions={versions} />
          </Box>
        </Flex>
      </Flex>
    </>
  );
}
