import { useEngineOutputsActions, useEngineOutputsState } from "@/store/useEngineOutputs";
import { createListCollection, Portal, Select, Span, Stack, Text } from "@chakra-ui/react";

type FlagItem = { value: string; label: string; description: string; group: string };

const flagGroups: { label: string; flags: FlagItem[] }[] = [
  {
    label: "AST",
    flags: [
      {
        value: "--print-ast",
        label: "print-ast",
        group: "AST",
        description: "Print the abstract syntax tree produced by the parser.",
      },
      {
        value: "--print-scopes",
        label: "print-scopes",
        group: "AST",
        description: "Print scope information (variable declarations and closures).",
      },
    ],
  },
  {
    label: "Bytecode",
    flags: [
      {
        value: "--print-bytecode",
        label: "print-bytecode",
        group: "Bytecode",
        description: "Print Ignition bytecode for each compiled function, including register layout.",
      },
    ],
  },
  {
    label: "Machine Code",
    flags: [
      {
        value: "--print-code",
        label: "print-code",
        group: "Machine Code",
        description: "Print all generated machine code (baseline and optimised tiers).",
      },
      {
        value: "--print-opt-code",
        label: "print-opt-code",
        group: "Machine Code",
        description: "Print only optimised (TurboFan) machine code when hot functions tier-up.",
      },
      {
        value: "--print-opt-source",
        label: "print-opt-source",
        group: "Machine Code",
        description: "Print the source of optimised functions alongside their machine code.",
      },
      {
        value: "--print-code-verbose",
        label: "print-code-verbose",
        group: "Machine Code",
        description: "Print machine code with verbose annotations (operand types, relocation info).",
      },
      {
        value: "--print-builtin-code",
        label: "print-builtin-code",
        group: "Machine Code",
        description: "Print machine code for V8 built-in functions (Array.map, Object.keys, etc.).",
      },
      {
        value: "--print-all-code",
        label: "print-all-code",
        group: "Machine Code",
        description: "Enable all print-code flags at once (implies print-code, print-opt-code, etc.).",
      },
    ],
  },
  {
    label: "RegExp",
    flags: [
      {
        value: "--print-regexp-code",
        label: "print-regexp-code",
        group: "RegExp",
        description: "Print machine code generated for regular expressions when they are JIT compiled.",
      },
      {
        value: "--print-regexp-bytecode",
        label: "print-regexp-bytecode",
        group: "RegExp",
        description: "Print bytecode emitted by the regexp interpreter for each compiled pattern.",
      },
      {
        value: "--print-regexp-graph",
        label: "print-regexp-graph",
        group: "RegExp",
        description: "Print the regexp graph (NFA/DFA structure) built during compilation.",
      },
    ],
  },
  {
    label: "Maglev",
    flags: [
      {
        value: "--print-maglev-code",
        label: "print-maglev-code",
        group: "Maglev",
        description: "Print machine code generated by the Maglev mid-tier JIT compiler.",
      },
      {
        value: "--print-maglev-graph",
        label: "print-maglev-graph",
        group: "Maglev",
        description: "Print the final Maglev IR graph after all optimisation passes.",
      },
      {
        value: "--print-maglev-graphs",
        label: "print-maglev-graphs",
        group: "Maglev",
        description: "Print the Maglev IR graph at every optimisation phase.",
      },
      {
        value: "--print-maglev-deopt-verbose",
        label: "print-maglev-deopt-verbose",
        group: "Maglev",
        description: "Print verbose deoptimisation information for Maglev-compiled code.",
      },
    ],
  },
  {
    label: "Turbolev",
    flags: [
      {
        value: "--print-turbolev-frontend",
        label: "print-turbolev-frontend",
        group: "Turbolev",
        description: "Print the Turbolev (TurboFan frontend) IR graph.",
      },
      {
        value: "--print-turbolev-inline-functions",
        label: "print-turbolev-inline-functions",
        group: "Turbolev",
        description: "Print information about functions inlined by Turbolev.",
      },
    ],
  },
  {
    label: "Wasm",
    flags: [
      {
        value: "--print-wasm-code",
        label: "print-wasm-code",
        group: "Wasm",
        description: "Print generated machine code for WebAssembly modules.",
      },
      {
        value: "--print-wasm-stub-code",
        label: "print-wasm-stub-code",
        group: "Wasm",
        description: "Print machine code for Wasm runtime stubs (call wrappers, trampoline code).",
      },
    ],
  },
  {
    label: "Trace",
    flags: [
      {
        value: "--trace-opt",
        label: "trace-opt",
        group: "Trace",
        description: "Trace when functions are selected for optimisation and their pipeline progression.",
      },
      {
        value: "--trace-opt-verbose",
        label: "trace-opt-verbose",
        group: "Trace",
        description: "Verbose optimisation trace including IR reductions, inlining decisions, and timing.",
      },
      {
        value: "--trace-deopt",
        label: "trace-deopt",
        group: "Trace",
        description: "Log every deoptimisation: bailout reason, source position, and reconstructed frame.",
      },
      {
        value: "--trace-ic",
        label: "trace-ic",
        group: "Trace",
        description: "Trace inline cache updates: monomorphic → polymorphic → megamorphic transitions.",
      },
      {
        value: "--trace-ignition",
        label: "trace-ignition",
        group: "Trace",
        description: "Trace Ignition interpreter dispatch: prints each bytecode as it executes.",
      },
      {
        value: "--trace-maps",
        label: "trace-maps",
        group: "Trace",
        description: "Trace hidden class (Map) creation and property transitions.",
      },
      {
        value: "--trace-maps-details",
        label: "trace-maps-details",
        group: "Trace",
        description: "Detailed hidden class transition info: descriptors, transition paths, and timestamps.",
      },
    ],
  },
  {
    label: "Misc",
    flags: [
      {
        value: "--allow-natives-syntax",
        label: "allow-natives-syntax",
        group: "Misc",
        description: "Allow use of V8 %intrinsics from JS (e.g. %OptimizeFunctionOnNextCall, %DebugPrint).",
      },
      {
        value: "--no-liftoff",
        label: "no-liftoff",
        group: "Misc",
        description: "Disable the Liftoff baseline Wasm compiler; use TurboFan directly for all Wasm.",
      },
      {
        value: "--no-wasm-async-compilation",
        label: "no-wasm-async-compilation",
        group: "Misc",
        description: "Compile WebAssembly modules synchronously instead of in background threads.",
      },
      {
        value: "--print-all-exceptions",
        label: "print-all-exceptions",
        group: "Misc",
        description: "Print all JS exceptions (including caught ones) as they are created.",
      },
      {
        value: "--print-break-location",
        label: "print-break-location",
        group: "Misc",
        description: "Print the source position each time a debug break is hit.",
      },
      {
        value: "--print-builtin-size",
        label: "print-builtin-size",
        group: "Misc",
        description: "Print the code size of each V8 built-in function after compilation.",
      },
      {
        value: "--print-deopt-stress",
        label: "print-deopt-stress",
        group: "Misc",
        description: "Print the number of deoptimisation stress points found in compiled code.",
      },
      {
        value: "--print-flag-values",
        label: "print-flag-values",
        group: "Misc",
        description: "Print the current value of every V8 flag at startup.",
      },
    ],
  },
];

const allFlags = flagGroups.flatMap((g) => g.flags);
const v8FlagOptions = createListCollection({ items: allFlags });

const V8FlagSelector = () => {
  const { selectedV8Flags } = useEngineOutputsState();
  const { setSelectedV8Flags } = useEngineOutputsActions();

  return (
    <Select.Root
      multiple
      collection={v8FlagOptions}
      size="sm"
      width="320px"
      value={selectedV8Flags}
      onValueChange={(e) => setSelectedV8Flags(e.value)}
    >
      <Select.Control>
        <Select.Trigger>
          <Select.ValueText placeholder="Select flags" />
        </Select.Trigger>
        <Select.IndicatorGroup>
          <Select.Indicator />
        </Select.IndicatorGroup>
      </Select.Control>
      <Portal>
        <Select.Positioner>
          <Select.Content>
            {flagGroups.map((group) => (
              <Select.ItemGroup key={group.label}>
                <Select.ItemGroupLabel>
                  <Text fontWeight="semibold" fontSize="xs" color="fg.muted" textTransform="uppercase">
                    {group.label}
                  </Text>
                </Select.ItemGroupLabel>
                {group.flags.map((flag) => (
                  <Select.Item item={flag} key={flag.value}>
                    <Stack gap="0">
                      <Select.ItemText>{flag.label}</Select.ItemText>
                      <Span color="fg.muted" textStyle="2xs">
                        {flag.description}
                      </Span>
                    </Stack>
                    <Select.ItemIndicator />
                  </Select.Item>
                ))}
              </Select.ItemGroup>
            ))}
          </Select.Content>
        </Select.Positioner>
      </Portal>
    </Select.Root>
  );
};

export default V8FlagSelector;
